### ISSUE TITLE
Productional version of tweakUI

### ISSUE THREAD

**Issue by Bluscream** [pathmann/pyTSon_plugins#1]
I am using some of the "test" plugins in here in my everyday teamspeak life. And most of 'em are working fine. But for the tweakUI thing i would like to have my layout saved. So it remembers that my chat is on the right side of the window tabbed infront of the info section.

https://github.com/pathmann/pyTSon/issues/9 could come in handy for it :P

**Comment by pathmann** [comment]
Feel free to fork it or just copy the code you need, but the purpose of the plugins here is to show pyTSon functionality, no productional use.
