### ISSUE TITLE
Example plugin with own GUI

### ISSUE THREAD

**Issue by Bluscream** [pathmann/pyTSon_plugins#2]
Can you create an example plugin that uses some kind of own GUI for other devs to look at?

**Comment by pathmann** [comment]
look at pyTSon's own code (ts3plugin.py and pytsonui.py).

Additionally, there are many sources on the internet on how to use Qt. The use of PythonQt is very to PyQt, so this is also a good starting point. 

Differences are described [here](http://pythonqt.sourceforge.net/Developer.html).

**Comment by Bluscream** [comment]
The pytsonui code is not nearly applyable in a script itself. If you don't wan't to make one thats fine but it would show off very nicely what pyTSon can do :)

**Comment by pathmann** [comment]
Same api for pyTSon's core as for plugins. So pytsonui is THE example to show off, what's possible.
